version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: usina-erp-db
    environment:
      POSTGRES_USER: usina
      POSTGRES_PASSWORD: usina123
      POSTGRES_DB: usina_erp
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
